version: '3.8'
services:
  slanggen-backend:
    # Zorgt ervoor dat Docker Compose eerst de image bouwt met de Dockerfile in deze map
    build:
      context: .
      dockerfile: Dockerfile
    image: slanggen-backend:latest
    container_name: slanggen_app
    # Mappen van hostpoort 80 naar containerpoort 8000
    ports:
      - "80:8000" 
    restart: always # Start de service automatisch op na een crash of hervatting van SURF