[data]
assets_dir = "assets"
artefacts_dir = "artefacts"
filename = "straattaal.txt"
url = "https://www.mijnwoordenboek.nl/dialect/Kerkraads"

[model]
embedding_dim = 32
hidden_dim = 64
num_layers = 2
vocab_size = 100

[training]
epochs = 800
learning_rate = 0.1
batch_size = 16
factor = 0.1
patience = 50
min_lr = 0.0001